[git_branch]
symbol = " "

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[gcloud]
format = '[$symbol$active]($style) '
style = 'bold yellow'

[os]
format = "on [($name )]($style)"
style = "bold blue"
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
pyenv_version_name = true

[sudo]
disabled = false
